version: '3'

services:
  client:
    container_name: opc_client
    image: opc_client:latest
    build: .
    depends_on:
      server:
        condition: service_healthy
    networks:
      - opc_net

  server:
    container_name: opc_server
    image: opc_server:latest
    build: ./server
    ports:
      - 4840:4840
      - 8080:8080
    volumes:
      - ./server/:/app/config
    networks:
      - opc_net
    healthcheck:
      test: echo "exit()" | uaclient -u server:4840
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 3s

networks:
  opc_net:
    driver: bridge

